# Generated by Django 5.2.4 on 2025-07-19 13:04

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('relationship_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='publication_year',
            field=models.IntegerField(default=2025),
            preserve_default=False,
        ),
    ]
