# Generated by Django 5.2.4 on 2025-08-01 19:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("relationship_app", "0002_book_publication_year"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="publication_year",
            field=models.IntegerField(default=2000),
        ),
        migrations.AlterField(
            model_name="librarian",
            name="library",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="librarian",
                to="relationship_app.library",
            ),
        ),
    ]
