# Generated by Django 5.2.5 on 2025-08-08 09:03

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Author",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Enter the full name of the author.", max_length=200
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(help_text="Title of the book.", max_length=200),
                ),
                (
                    "publication_year",
                    models.IntegerField(
                        help_text="Year the book was published.",
                        validators=[
                            django.core.validators.MinValueValidator(
                                1000, message="Year must be at least 1000."
                            ),
                            django.core.validators.MaxValueValidator(
                                2025,
                                message="Publication year cannot be in the future.",
                            ),
                        ],
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        help_text="The author of this book.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="books",
                        to="api.author",
                    ),
                ),
            ],
            options={
                "ordering": ["title"],
            },
        ),
    ]
