# Generated by Django 5.2.4 on 2025-07-09 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookshelf", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="publication_year",
            field=models.IntegerField(default=1900, verbose_name=1900),
            preserve_default=False,
        ),
    ]
